# Generated by Django 5.2.13 on 2026-05-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('paid_leave', 'Paid Leave'), ('half_day', 'Half Day'), ('overtime', 'Overtime')], default='present', max_length=20),
        ),
    ]
